format = """
[î‚²](#F8D84E)\
$os$username\
[î‚°](bg:#5A3E2B fg:#F8D84E)\
$directory\
[î‚°](fg:#5A3E2B bg:#67D3C2)\
$git_branch\
$git_status\
[î‚°](fg:#67D3C2 bg:#D8C39F)\
$python\
[î‚°](fg:#D8C39F bg:#374151)\
$docker_context\
[î‚°](fg:#374151 bg:#111827)\
$time\
[î‚° ](fg:#111827)\
$cmd_duration
"""

command_timeout = 2000

# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
[os]
disabled = false
style = "bg:#F8D84E fg:#1E1E1E"
[os.symbols]
Macos = "ïŒ‚ "
Ubuntu = "ïŒ› "

[username]
show_always = true
style_user = "bg:#F8D84E fg:#1E1E1E"
style_root = "bg:#F8D84E fg:#1E1E1E"
format = '[ $user ]($style)'

[directory]
style = "bg:#5A3E2B fg:#F8D84E"
format = "[ $path]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
[directory.substitutions]
"Documents" = "ğŸ“„  "
"Downloads" = "ğŸ“¥  "
"workspace" = "ğŸ–¥ï¸  "

[git_branch]
symbol = "ï˜"
style = "bg:#67D3C2 fg:#1E1E1E"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#67D3C2 fg:#1E1E1E"
format = '[ $all_status$ahead_behind ]($style)'

[python]
symbol = "ğŸ"
style = "bg:#D8C39F fg:#1E1E1E"
format = '[ $symbol ($version) ($virtualenv) ]($style)'

[docker_context]
symbol = "ğŸ³"
style = "bg:#374151 fg:#F8D84E"
format = '[ $symbol $context ]($style)'

[time]
disabled = false
time_format = "%T"
style = "bg:#111827 fg:#E5E7EB"
format = '[ â± $time ]($style)'

[cmd_duration]
format = "[â³ $duration ]($style)"
style = "fg:#D8C39F"

